<?php 
$enabled = Mage::getStoreConfig('poboxrestrictions/general/enabled');
$messageEnabled = Mage::getStoreConfig('poboxrestrictions/warning/enabled');
if ($enabled == true && $messageEnabled == true) {
    $message = Mage::getStoreConfig('poboxrestrictions/warning/message');
    if ($message != '') {
?>
<script type='text/javascript'>
$(document).observe("dom:loaded", function(){
    $$('label[for=shipping:street1]')[0].insert({
        before: "<div id='poboxrestrictions-warning'><?php echo htmlspecialchars($message); ?></div>"
    });
});
</script>
<?php
    }
}
